
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper1
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    container_name: kafa1
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"

  #mqtt5:
  #  image: eclipse-mosquitto
  #  container_name: mqtt51
  #  ports:
      #- ${MOSQUITTO_PORT_DEFAULT}+":"+${MOSQUITTO_PORT_DEFAULT}  #default mqtt port
      #- ${MOSQUITTO_PORT_WEBSOCKET}+":"+${MOSQUITTO_PORT_WEBSOCKET} #default mqtt port for websockets
  #    - 1883:1883
  #    - 9001:9001
  #  volumes:
  #    - ./mosquitto/config:/mosquitto/config:rw
  #    - ./mosquitto/data:/mosquitto/data:rw
  #    - ./mosquitto/log:/mosquitto/log:rw
  #  restart: unless-stopped
    
  influxdb:
    image: 'influxdb:latest'
    container_name: influxdb1
    ports:
      #- ${INFLUX_PORT}+":"+${INFLUX_PORT}    
      - 8086:8086

    environment:
      #DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUX_ORGANIZZATION}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUX_BUCKET}
      #DOCKER_INFLUXDB_INIT_RETENTION: 30d
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN}
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana1
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_FEATURE_TOGGLES_ALLOW_EMBEDDING=true
      - GF_SECURITY_X_CONTENT_TYPE_OPTIONS=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
    volumes:
      - ./grafana_data:/var/lib/grafana
    restart: always
    #depends_on:
    #  - renderer
    
  #renderer:  
  #  image: grafana/grafana-image-renderer:latest
  #  container_name: grafana-renderer1
  #  ports:
  #    - "8081:8081"
  #  restart: unless-stopped
   
  telegraf:
    image: telegraf:latest
    container_name: telegraf1
    restart: always
    depends_on:
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - HOSTNAME=telegraf
      - INFLUXDB_URL=http://influxdb1:8086